# Generated by Django 4.2.1 on 2023-07-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0004_alter_car_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fuel_type',
            },
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmodel', to='relationship.car'),
        ),
        migrations.CreateModel(
            name='FourWheeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fueltype', models.ManyToManyField(to='relationship.fueltype')),
            ],
            options={
                'db_table': 'fourwheelers',
            },
        ),
    ]
