# Generated by Django 4.2.1 on 2023-07-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0005_fueltype_alter_carmodel_car_fourwheeler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourwheeler',
            name='fueltype',
        ),
        migrations.AlterModelTable(
            name='fourwheeler',
            table=None,
        ),
        migrations.CreateModel(
            name='CModel_Fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_field', models.CharField(max_length=225)),
                ('cmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationship.fourwheeler')),
                ('fueltype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationship.fueltype')),
            ],
            options={
                'unique_together': {('cmodel', 'fueltype')},
            },
        ),
    ]
